services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - database
    restart: always
    volumes:
      - .:/app
    command: ["python3", "main.py"]

  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pg_data:
